#!/usr/bin/env Rscript

########################################################################################
#### Author: Sunny Piya                                                             ####
#### Purpose: Import multple csv files containing survey (general recruitment data) ####
#### and extract the demo data into a single csv file for final upload to TA        ####
########################################################################################

#take arguments from the command line.
#first argument is the location of the R script
#second argument is the location of the filer containing csv files (survey output)
args = commandArgs(trailingOnly = TRUE)
first_input<-args[1]

if (length(args)!=1) {
  stop(Sys.getenv("Please make sure to inclde 'Rscript <Path to the R script location> <Path to the directory location with survey files>!!!", call.=FALSE))
} 

#load required packages if they are not installed on your machine
if (!require("sqldf")) {
  install.packages("sqldf", repos="http://cran.rstudio.com/") 
  library("sqldf")
}

#set working directory
setwd(first_input)
 
#function to remove the first row in each data frame within the master dataframe list
remove_row1 <- function(df){
  df[-1,]
}

#final all matching files with .csv extension in the working directory
file_list<-list.files(pattern="*.csv")

#import all survey .csv files from the directory into R, remove first row, and assign all dataframe to a list
dflistnew <- list()
for (i in 1:length(file_list)){
  dflistnew[[length(dflistnew)+1]] <- assign(file_list[i], remove_row1(read.csv(file_list[i])))
}

#select only useful fields from the raw .csv files 
dflisttrim <- list()
for (j in 1:length(dflistnew)){
             dflisttrim[[j]] <- data.frame(dflistnew[[j]]$email,
                                                   dflistnew[[j]]$RegR,
                                                   dflistnew[[j]]$SegR,
                                                   dflistnew[[j]]$WorkFocus,
                                                   dflistnew[[j]]$EmpSector,
                                                   dflistnew[[j]]$EmpSector_TEXT,
                                                   dflistnew[[j]]$job,
                                                   dflistnew[[j]]$job_TEXT,
                                                   dflistnew[[j]]$cjob,
                                                   dflistnew[[j]]$cjob_TEXT,
                                                   dflistnew[[j]]$country,
                                                   dflistnew[[j]]$Salutation,
                                                   dflistnew[[j]]$Name_1_TEXT,
                                                   dflistnew[[j]]$Name_2_TEXT,
                                                   dflistnew[[j]]$degree_1,
                                                   dflistnew[[j]]$degree_2,
                                                   dflistnew[[j]]$degree_3,
                                                   dflistnew[[j]]$degree_4,
                                                   dflistnew[[j]]$degree_5,
                                                   dflistnew[[j]]$degree_6,
                                                   dflistnew[[j]]$degree_7,
                                                   dflistnew[[j]]$Contact_1_TEXT,
                                                   dflistnew[[j]]$Contact_2_TEXT,
                                                   dflistnew[[j]]$Contact_3_TEXT,
                                                   dflistnew[[j]]$Contact_4_TEXT,
                                                   dflistnew[[j]]$Contact_5_TEXT,
                                                   dflistnew[[j]]$Contact_6_TEXT,
                                                   dflistnew[[j]]$RA_1,
                                                   dflistnew[[j]]$RA_2,
                                                   dflistnew[[j]]$RA_3,
                                                   dflistnew[[j]]$RA_4,
                                                   dflistnew[[j]]$RA_5,
                                                   dflistnew[[j]]$RA_6,
                                                   dflistnew[[j]]$RA_7,
                                                   dflistnew[[j]]$RA_8,
                                                   dflistnew[[j]]$RA_9,
                                                   dflistnew[[j]]$RA_10,
                                                   dflistnew[[j]]$RA_11,
                                                   dflistnew[[j]]$RA_12,
                                                   dflistnew[[j]]$RA_13,
                                                   dflistnew[[j]]$RA_14,
                                                   dflistnew[[j]]$RA_15,
                                                   dflistnew[[j]]$RA_16,
                                                   dflistnew[[j]]$RA_17,
                                                   dflistnew[[j]]$RA_18,
                                                   dflistnew[[j]]$RA_19,
                                                   dflistnew[[j]]$RA_20,
                                                   dflistnew[[j]]$RA_21,
                                                   dflistnew[[j]]$RA_22,
                                                   dflistnew[[j]]$RA_23,
                                                   dflistnew[[j]]$RA_24,
                                                   dflistnew[[j]]$RA_25,
                                                   dflistnew[[j]]$RA_26,
                                                   dflistnew[[j]]$RA_27,
                                                   dflistnew[[j]]$RA_28,
                                                   dflistnew[[j]]$RA_29,
                                                   dflistnew[[j]]$RA_30,
                                                   dflistnew[[j]]$RA_31,
                                                   dflistnew[[j]]$RA_32,
                                                   dflistnew[[j]]$RA_33,
                                                   dflistnew[[j]]$RA_34,
                                                   dflistnew[[j]]$RA_35,
                                                   dflistnew[[j]]$RA_36,
                                                   dflistnew[[j]]$RA_37,
                                                   dflistnew[[j]]$RA_38,
                                                   dflistnew[[j]]$RA_39,
                                                   dflistnew[[j]]$RA_40,
                                                   dflistnew[[j]]$RA_41,
                                                   dflistnew[[j]]$RA_42,
                                                   dflistnew[[j]]$RA_42_TEXT,
                                                   dflistnew[[j]]$Core,
                                                   dflistnew[[j]]$TT_1,
                                                   dflistnew[[j]]$TT_2,
                                                   dflistnew[[j]]$TT_3,
                                                   dflistnew[[j]]$TT_4,
                                                   dflistnew[[j]]$TT_5,
                                                   dflistnew[[j]]$TT_6,
                                                   dflistnew[[j]]$TT_7,
                                                   dflistnew[[j]]$TT_8,
                                                   dflistnew[[j]]$TT_9,
                                                   dflistnew[[j]]$TT_10,
                                                   dflistnew[[j]]$TT_11,
                                                   dflistnew[[j]]$TT_12,
                                                   dflistnew[[j]]$TT_13,
                                                   dflistnew[[j]]$TT_14,
                                                   dflistnew[[j]]$TT_15,
                                                   dflistnew[[j]]$TT_16,
                                                   dflistnew[[j]]$TT_17,
                                                   dflistnew[[j]]$TT_18,
                                                   dflistnew[[j]]$TT_19,
                                                   dflistnew[[j]]$TT_20,
                                                   dflistnew[[j]]$TT_21,
                                                   dflistnew[[j]]$TT_22,
                                                   dflistnew[[j]]$TT_23,
                                                   dflistnew[[j]]$TT_24,
                                                   dflistnew[[j]]$TT_25,
                                                   dflistnew[[j]]$TT_26,
                                                   dflistnew[[j]]$TT_27,
                                                   dflistnew[[j]]$TT_28,
                                                   dflistnew[[j]]$TT_29,
                                                   dflistnew[[j]]$TT_30,
                                                   dflistnew[[j]]$TT_31,
                                                   dflistnew[[j]]$TT_32,
                                                   dflistnew[[j]]$TT_33,
                                                   dflistnew[[j]]$TT_33_TEXT,
                                                   dflistnew[[j]]$CDD_1,
                                                   dflistnew[[j]]$CDD_2,
                                                   dflistnew[[j]]$CDD_3,
                                                   dflistnew[[j]]$CDD_4,
                                                   dflistnew[[j]]$CDD_5,
                                                   dflistnew[[j]]$CDD_6,
                                                   dflistnew[[j]]$CDD_7,
                                                   dflistnew[[j]]$CDD_8,
                                                   dflistnew[[j]]$CDD_9,
                                                   dflistnew[[j]]$CDD_10,
                                                   dflistnew[[j]]$CDD_11,
                                                   dflistnew[[j]]$CDD_12,
                                                   dflistnew[[j]]$CDD_13,
                                                   dflistnew[[j]]$CDD_13_TEXT,
                                                   dflistnew[[j]]$LabType,
                                                   dflistnew[[j]]$SciDisp_1,
                                                   dflistnew[[j]]$SciDisp_2,
                                                   dflistnew[[j]]$SciDisp_3,
                                                   dflistnew[[j]]$SciDisp_4,
                                                   dflistnew[[j]]$SciDisp_5,
                                                   dflistnew[[j]]$SciDisp_6,
                                                   dflistnew[[j]]$SciDisp_7,
                                                   dflistnew[[j]]$SciDisp_8,
                                                   dflistnew[[j]]$SciDisp_8_TEXT,
                                                   dflistnew[[j]]$FoodBev_1,
                                                   dflistnew[[j]]$FoodBev_2,
                                                   dflistnew[[j]]$FoodBev_3,
                                                   dflistnew[[j]]$FoodBev_4,
                                                   dflistnew[[j]]$FoodBev_5,
                                                   dflistnew[[j]]$FoodBev_6,
                                                   dflistnew[[j]]$FoodBev_7,
                                                   dflistnew[[j]]$FoodBev_7_TEXT,
                                                   dflistnew[[j]]$ForenSci_1,
                                                   dflistnew[[j]]$ForenSci_2,
                                                   dflistnew[[j]]$DrugRole_1,
                                                   dflistnew[[j]]$DrugRole_2,
                                                   dflistnew[[j]]$DrugRole_3,
                                                   dflistnew[[j]]$DrugRole_4,
                                                   dflistnew[[j]]$DrugRole_5,
                                                   dflistnew[[j]]$DrugRole_6,
                                                   dflistnew[[j]]$DrugRole_7,
                                                   dflistnew[[j]]$DrugRole_7_TEXT,
                                                   dflistnew[[j]]$ToM_1,
                                                   dflistnew[[j]]$ToM_2,
                                                   dflistnew[[j]]$ToM_3,
                                                   dflistnew[[j]]$ToM_4,
                                                   dflistnew[[j]]$ToM_5,
                                                   dflistnew[[j]]$ToM_6,
                                                   dflistnew[[j]]$ToM_7,
                                                   dflistnew[[j]]$ToM_7_TEXT,
                                                   dflistnew[[j]]$Certs_1,
                                                   dflistnew[[j]]$Certs_2,
                                                   dflistnew[[j]]$Certs_3,
                                                   dflistnew[[j]]$Certs_4,
                                                   dflistnew[[j]]$Certs_5,
                                                   dflistnew[[j]]$Certs_6,
                                                   dflistnew[[j]]$Certs_7,
                                                   dflistnew[[j]]$Certs_8,
                                                   dflistnew[[j]]$Certs_9,
                                                   dflistnew[[j]]$Certs_10,
                                                   dflistnew[[j]]$Certs_11,
                                                   dflistnew[[j]]$Certs_12,
                                                   dflistnew[[j]]$Certs_13,
                                                   dflistnew[[j]]$Certs_14,
                                                   dflistnew[[j]]$Certs_15,
                                                   dflistnew[[j]]$Certs_16,
                                                   dflistnew[[j]]$Certs_17,
                                                   dflistnew[[j]]$Certs_18,
                                                   dflistnew[[j]]$Certs_19,
                                                   dflistnew[[j]]$Certs_20,
                                                   dflistnew[[j]]$Certs_21,
                                                   dflistnew[[j]]$Certs_22,
                                                   dflistnew[[j]]$Certs_23,
                                                   dflistnew[[j]]$Certs_24,
                                                   dflistnew[[j]]$Certs_25,
                                                   dflistnew[[j]]$Certs_26,
                                                   dflistnew[[j]]$Certs_27,
                                                   dflistnew[[j]]$Certs_27_TEXT,
                                                   dflistnew[[j]]$Certs_28,
                                                   dflistnew[[j]]$Dis_1,
                                                   dflistnew[[j]]$Dis_2,
                                                   dflistnew[[j]]$Dis_3,
                                                   dflistnew[[j]]$Dis_4,
                                                   dflistnew[[j]]$Dis_5,
                                                   dflistnew[[j]]$Dis_6,
                                                   dflistnew[[j]]$Dis_7,
                                                   dflistnew[[j]]$Dis_8,
                                                   dflistnew[[j]]$Dis_9,
                                                   dflistnew[[j]]$Dis_9_TEXT,
                                                   dflistnew[[j]]$Dis_10,
                                                   dflistnew[[j]]$Canc_1,
                                                   dflistnew[[j]]$Canc_2,
                                                   dflistnew[[j]]$Canc_3,
                                                   dflistnew[[j]]$Canc_4,
                                                   dflistnew[[j]]$Canc_5,
                                                   dflistnew[[j]]$Canc_6,
                                                   dflistnew[[j]]$Canc_7,
                                                   dflistnew[[j]]$Canc_8,
                                                   dflistnew[[j]]$Canc_9,
                                                   dflistnew[[j]]$Canc_10,
                                                   dflistnew[[j]]$Canc_11,
                                                   dflistnew[[j]]$Canc_12,
                                                   dflistnew[[j]]$Canc_13,
                                                   dflistnew[[j]]$Canc_14,
                                                   dflistnew[[j]]$Canc_15,
                                                   dflistnew[[j]]$Canc_16,
                                                   dflistnew[[j]]$Canc_17,
                                                   dflistnew[[j]]$Canc_18,
                                                   dflistnew[[j]]$Canc_19,
                                                   dflistnew[[j]]$Canc_19_TEXT,
                                                   dflistnew[[j]]$NumBeds,
                                                   dflistnew[[j]]$CompletionStatus,
                                                   stringsAsFactors = FALSE)
    }

#bind all rows for trimmed dataframes to create a single dataframe
dflisttrim_rbind<-do.call("rbind", dflisttrim)
         
#Replace column names of the dataframe with new column names based on the Target Audience requirements
colnames(dflisttrim_rbind) <- c("Email",
                          "Continent",
                          "Segment",
                          "Research/Work Focus",
                          "Employment Sector",
                          "Employment Sector - Other",
                          "Job Position",
                          "Job Position - Other",
                          "Clinical Job Position",
                          "Clinical Job Position - Other",
                          "Country",
                          "Salutation",
                          "FirstName",
                          "LastName",
                          "Degree_1",
                          "Degree_2",
                          "Degree_3",
                          "Degree_4",
                          "Degree_5",
                          "Degree_6",
                          "Degree_7",
                          "Organization",
                          "Department",
                          "City",
                          "State/Province",
                          "Zip/Postal Code",
                          "Phone",
                          "RA - Agriculture",
                          "RA - Analytical Chemistry",
                          "RA - Anatomy",
                          "RA - Biochemistry",
                          "RA - Biodefense",
                          "RA - Bioinformatics",
                          "RA - Biophysics",
                          "RA - Bioprocessing",
                          "RA - Biostatistics",
                          "RA - Botany",
                          "RA - Cancer/Oncology",
                          "RA - Cell Biology",
                          "RA - Clinical Diagnostics",
                          "RA - Developmental Biology",
                          "RA - Drug Discovery/R&D",
                          "RA - Environmental Science",
                          "RA - Epigenetics/Epigenomics",
                          "RA - Food Science",
                          "RA - Forensics",
                          "RA - Gene Therapy",
                          "RA - Genetics/Genomics",
                          "RA - Hematology",
                          "RA - Histology",
                          "RA - Immunology/Virology",
                          "RA - Material Sciences/Ploymer Chemistry",
                          "RA - Medicinal Chemistry",
                          "RA - Microbiology",
                          "RA - Molecular Biology",
                          "RA - Molecular Diagnostics",
                          "RA - Nanotechnology",
                          "RA - Neuroscience",
                          "RA - Organic Chemistry",
                          "RA - Pathology",
                          "RA - Pharmacogenomics",
                          "RA - Protein Sciences",
                          "RA - Proteomics",
                          "RA - Regenerative",
                          "RA - Stem Cell Biology",
                          "RA - Synthetic Biology",
                          "RA - Toxicology",
                          "RA - Zoology",
                          "RA - Other (please specify)",
                          "Research Areas - Other",
                          "Core",
                          "TT - Bacteria Culture",
                          "TT - Cell-Based Assays",
                          "TT - Confocal Microscopy",
                          "TT - Eukaryotic Cell/Tissue Culture",
                          "TT - Flow Cytometry",
                          "TT - Fluorescence Microscopy",
                          "TT - Gene Expression Analysis",
                          "TT - High Content Screening",
                          "TT - High-Throughput Screening (HTS)",
                          "TT - Immunohistochemistry",
                          "TT - Light Microscopy",
                          "TT - Stem Cell Culture/Analysis",
                          "TT - Classical End-Point PCR",
                          "TT - Cloning/Molecular Biology Techniques",
                          "TT - DNA/RNA Microarrays",
                          "TT - Genotyping",
                          "TT - Next Generation Sequencing",
                          "TT - Real-Time PCR (including qPCR and RT-PCR)",
                          "TT - RNAi (including siRNA, miRNA)",
                          "TT - Sanger DNA Sequencing",
                          "TT - Single Nucleotide Polymorphism (including genotyping, discovery, validation)",
                          "TT - 2-D Gel Electrophoresis",
                          "TT - Calorimetry (including ITC, DSC)",
                          "TT - Chromatography",
                          "TT - Enzyme-linked Immunosorbent Assay (ELISA)",
                          "TT - Label-Free Detection/Analysis (Including Biosensors, SPR, etc.)",
                          "TT - Light Scattering (MALS, DLS)",
                          "TT - Mass Spectrometry",
                          "TT - Multiplex Bead Assays",
                          "TT - Protein Purification & Separation",
                          "TT - Protein Structural Analysis (NMR, X-Ray Crystallography, CD, etc.)",
                          "TT - Western Blotting",
                          "TT - Other Tools or Techniques (please specify)",
                          "Tools/Techniques - Other",
                          "CDD - Blood Bank",
                          "CDD - Clinical Chemistry",
                          "CDD - Cytopathology",
                          "CDD - Diagnostic Imaging/Radiology",
                          "CDD - Drug Testing",
                          "CDD - Hematology and Coagulation",
                          "CDD - Histopathology",
                          "CDD - Immunology",
                          "CDD - Microbiology",
                          "CDD - Molecular Diagnostics and Genetics (including pharmacogenomic and prenatal testing)",
                          "CDD - Toxicology",
                          "CDD - Urinalysis",
                          "CDD - Other",
                          "CDD - Other (please specify)",
                          "Laboratory Type",
                          "Scientific Discipline - Agriculture",
                          "Scientific Discipline - Chemistry",
                          "Scientific Discipline - Environmental Sciences",
                          "Scientific Discipline - Food/Beverage",
                          "Scientific Discipline - Material Sciences",
                          "Scientific Discipline - Nanotechnology",
                          "Scientific Discipline - Physical Sciences",
                          "Scientific Discipline - Other",
                          "Scientific Discipline - Other (please specify)",
                          "Food/Beverage Science - Research",
                          "Food/Beverage Science - Product R&D",
                          "Food/Beverage Science - Flavor Chemistry/Sensory Science",
                          "Food/Beverage Science - QA/QC",
                          "Food/Beverage Science - Food/Beverage Microbiology",
                          "Food/Beverage Science - Regulations/Compliance",
                          "Food/Beverage Science - Other",
                          "Food/Beverage Science - Other (please specify)",
                          "ForenSci - Physical Examinations",
                          "ForenSci - Biological/Medical Examination",
                          "Biopharmaceutical Drug Development Role - Assay Development",
                          "Biopharmaceutical Drug Development Role - Downstream Process Development",
                          "Biopharmaceutical Drug Development Role - Formulation Development",
                          "Biopharmaceutical Drug Development Role - Manufacturing",
                          "Biopharmaceutical Drug Development Role - QA/QC",
                          "Biopharmaceutical Drug Development Role - Upstream Process Development",
                          "Biopharmaceutical Drug Development Role - Other",
                          "Biopharmaceutical Drug Development Role - Other (please specify)",
                          "ToM - Cell Based Therapies",
                          "ToM - Monoclonal Antibodies (mAbs)",
                          "ToM - Non-Antibody Protein Therapeutics",
                          "ToM - Nucleic Acid Based Therapeutics",
                          "ToM - Small Molecule Therapeutics",
                          "ToM - Vaccines",
                          "ToM - Other",
                          "ToM - Other (please specify)",
                          "Cert - Allergy and Immunology",
                          "Cert - Anesthesiology",
                          "Cert - Colon and Rectal Surgery",
                          "Cert - Dermatology",
                          "Cert - Emergency Medicine",
                          "Cert - Family Medicine",
                          "Cert - Internal Medicine",
                          "Cert - Medical Genetics",
                          "Cert - Neurological Surgery",
                          "Cert - Neurology",
                          "Cert - Nuclear Medicine",
                          "Cert - Obstetrics and Gynecology",
                          "Cert - Ophthalmology",
                          "Cert - Orthopaedic Surgery",
                          "Cert - Otolaryngology",
                          "Cert - Pathology",
                          "Cert - Pediatrics",
                          "Cert - Physical Medicine and Rehabilitation",
                          "Cert - Plastic Surgery",
                          "Cert - Preventive Medicine",
                          "Cert - Psychiatry",
                          "Cert - Radiation Oncology",
                          "Cert - Radiology",
                          "Cert - Surgery",
                          "Cert - Thoracic Surgery",
                          "Cert - Urology",
                          "Cert - Other",
                          "Cert - Other (please specify)",
                          "Cert - I do not have any board certifications",
                          "Dis - Autoimmune disease",
                          "Dis - Cancer",
                          "Dis - Cardiovascular disease",
                          "Dis - Diabetes",
                          "Dis - Endocrine system disorders",
                          "Dis - Infectious diseases",
                          "Dis - Inflammation",
                          "Dis - Neurological disorders",
                          "Dis - Other",
                          "Dis - Other (please specify)",
                          "Dis - My work does not focus on any particular disease",
                          "Canc - Bladder",
                          "Canc - Brain",
                          "Canc - Breast",
                          "Canc - Cervical",
                          "Canc - CNS, not brain",
                          "Canc - Colon/rectal",
                          "Canc - Esophagus",
                          "Canc - Kidney",
                          "Canc - Leukemia",
                          "Canc - Liver",
                          "Canc - Lung",
                          "Canc - Lymphoma",
                          "Canc - Melanoma",
                          "Canc - Neuroblastoma",
                          "Canc - Ovarian",
                          "Canc - Pancreas",
                          "Canc - Prostate",
                          "Canc - Uterine",
                          "Canc - Other",
                          "Canc - Other (please specify)",
                          "Number of Beds",
                          "CompletionStatus")

#Modify colums as desired for the final output data frame
#only select records where the CompletionStatus = 'Complete'
dffinal<-sqldf('select
               "Email",
               "Continent",
               "Segment",
               "Research/Work Focus",
               "Employment Sector",
               "Employment Sector - Other",
               "Job Position",
               "Job Position - Other",
               "Clinical Job Position",
               "Clinical Job Position - Other",
               "Country",
               "Salutation",
               "FirstName",
               "LastName",
               "Degree_1"||"/"||"Degree_2"||"/"||"Degree_3"||"/"||"Degree_4"||"/"||"Degree_5"||"/"||"Degree_6"||"/"||"Degree_7" as Degree,
               "Organization",
               "Department",
               "City",
               "State/Province",
               "Zip/Postal Code",
               "Phone",
               "RA - Agriculture",
               "RA - Analytical Chemistry",
               "RA - Anatomy",
               "RA - Biochemistry",
               "RA - Biodefense",
               "RA - Bioinformatics",
               "RA - Biophysics",
               "RA - Bioprocessing",
               "RA - Biostatistics",
               "RA - Botany",
               "RA - Cancer/Oncology",
               "RA - Cell Biology",
               "RA - Clinical Diagnostics",
               "RA - Developmental Biology",
               "RA - Drug Discovery/R&D",
               "RA - Environmental Science",
               "RA - Epigenetics/Epigenomics",
               "RA - Food Science",
               "RA - Forensics",
               "RA - Gene Therapy",
               "RA - Genetics/Genomics",
               "RA - Hematology",
               "RA - Histology",
               "RA - Immunology/Virology",
               "RA - Material Sciences/Ploymer Chemistry",
               "RA - Medicinal Chemistry",
               "RA - Microbiology",
               "RA - Molecular Biology",
               "RA - Molecular Diagnostics",
               "RA - Nanotechnology",
               "RA - Neuroscience",
               "RA - Organic Chemistry",
               "RA - Pathology",
               "RA - Pharmacogenomics",
               "RA - Protein Sciences",
               "RA - Proteomics",
               "RA - Regenerative",
               "RA - Stem Cell Biology",
               "RA - Synthetic Biology",
               "RA - Toxicology",
               "RA - Zoology",
               "RA - Other (please specify)",
               "Research Areas - Other",
               "Core",
               "TT - Bacteria Culture",
               "TT - Cell-Based Assays",
               "TT - Confocal Microscopy",
               "TT - Eukaryotic Cell/Tissue Culture",
               "TT - Flow Cytometry",
               "TT - Fluorescence Microscopy",
               "TT - Gene Expression Analysis",
               "TT - High Content Screening",
               "TT - High-Throughput Screening (HTS)",
               "TT - Immunohistochemistry",
               "TT - Light Microscopy",
               "TT - Stem Cell Culture/Analysis",
               "TT - Classical End-Point PCR",
               "TT - Cloning/Molecular Biology Techniques",
               "TT - DNA/RNA Microarrays",
               "TT - Genotyping",
               "TT - Next Generation Sequencing",
               "TT - Real-Time PCR (including qPCR and RT-PCR)",
               "TT - RNAi (including siRNA, miRNA)",
               "TT - Sanger DNA Sequencing",
               "TT - Single Nucleotide Polymorphism (including genotyping, discovery, validation)",
               "TT - 2-D Gel Electrophoresis",
               "TT - Calorimetry (including ITC, DSC)",
               "TT - Chromatography",
               "TT - Enzyme-linked Immunosorbent Assay (ELISA)",
               "TT - Label-Free Detection/Analysis (Including Biosensors, SPR, etc.)",
               "TT - Light Scattering (MALS, DLS)",
               "TT - Mass Spectrometry",
               "TT - Multiplex Bead Assays",
               "TT - Protein Purification & Separation",
               "TT - Protein Structural Analysis (NMR, X-Ray Crystallography, CD, etc.)",
               "TT - Western Blotting",
               "TT - Other Tools or Techniques (please specify)",
               "Tools/Techniques - Other",
               "CDD - Blood Bank",
               "CDD - Clinical Chemistry",
               "CDD - Cytopathology",
               "CDD - Diagnostic Imaging/Radiology",
               "CDD - Drug Testing",
               "CDD - Hematology and Coagulation",
               "CDD - Histopathology",
               "CDD - Immunology",
               "CDD - Microbiology",
               "CDD - Molecular Diagnostics and Genetics (including pharmacogenomic and prenatal testing)",
               "CDD - Toxicology",
               "CDD - Urinalysis",
               "CDD - Other",
               "CDD - Other (please specify)",
               "Laboratory Type",
               "Scientific Discipline - Agriculture",
               "Scientific Discipline - Chemistry",
               "Scientific Discipline - Environmental Sciences",
               "Scientific Discipline - Food/Beverage",
               "Scientific Discipline - Material Sciences",
               "Scientific Discipline - Nanotechnology",
               "Scientific Discipline - Physical Sciences",
               "Scientific Discipline - Other",
               "Scientific Discipline - Other (please specify)",
               "Food/Beverage Science - Research",
               "Food/Beverage Science - Product R&D",
               "Food/Beverage Science - Flavor Chemistry/Sensory Science",
               "Food/Beverage Science - QA/QC",
               "Food/Beverage Science - Food/Beverage Microbiology",
               "Food/Beverage Science - Regulations/Compliance",
               "Food/Beverage Science - Other",
               "Food/Beverage Science - Other (please specify)",
               "ForenSci - Physical Examinations",
               "ForenSci - Biological/Medical Examination",
               "Biopharmaceutical Drug Development Role - Assay Development",
               "Biopharmaceutical Drug Development Role - Downstream Process Development",
               "Biopharmaceutical Drug Development Role - Formulation Development",
               "Biopharmaceutical Drug Development Role - Manufacturing",
               "Biopharmaceutical Drug Development Role - QA/QC",
               "Biopharmaceutical Drug Development Role - Upstream Process Development",
               "Biopharmaceutical Drug Development Role - Other",
               "Biopharmaceutical Drug Development Role - Other (please specify)",
               "ToM - Cell Based Therapies",
               "ToM - Monoclonal Antibodies (mAbs)",
               "ToM - Non-Antibody Protein Therapeutics",
               "ToM - Nucleic Acid Based Therapeutics",
               "ToM - Small Molecule Therapeutics",
               "ToM - Vaccines",
               "ToM - Other",
               "ToM - Other (please specify)",
               "Cert - Allergy and Immunology",
               "Cert - Anesthesiology",
               "Cert - Colon and Rectal Surgery",
               "Cert - Dermatology",
               "Cert - Emergency Medicine",
               "Cert - Family Medicine",
               "Cert - Internal Medicine",
               "Cert - Medical Genetics",
               "Cert - Neurological Surgery",
               "Cert - Neurology",
               "Cert - Nuclear Medicine",
               "Cert - Obstetrics and Gynecology",
               "Cert - Ophthalmology",
               "Cert - Orthopaedic Surgery",
               "Cert - Otolaryngology",
               "Cert - Pathology",
               "Cert - Pediatrics",
               "Cert - Physical Medicine and Rehabilitation",
               "Cert - Plastic Surgery",
               "Cert - Preventive Medicine",
               "Cert - Psychiatry",
               "Cert - Radiation Oncology",
               "Cert - Radiology",
               "Cert - Surgery",
               "Cert - Thoracic Surgery",
               "Cert - Urology",
               "Cert - Other",
               "Cert - Other (please specify)",
               "Cert - I do not have any board certifications",
               "Dis - Autoimmune disease",
               "Dis - Cancer",
               "Dis - Cardiovascular disease",
               "Dis - Diabetes",
               "Dis - Endocrine system disorders",
               "Dis - Infectious diseases",
               "Dis - Inflammation",
               "Dis - Neurological disorders",
               "Dis - Other",
               "Dis - Other (please specify)",
               "Dis - My work does not focus on any particular disease",
               "Canc - Bladder",
               "Canc - Brain",
               "Canc - Breast",
               "Canc - Cervical",
               "Canc - CNS, not brain",
               "Canc - Colon/rectal",
               "Canc - Esophagus",
               "Canc - Kidney",
               "Canc - Leukemia",
               "Canc - Liver",
               "Canc - Lung",
               "Canc - Lymphoma",
               "Canc - Melanoma",
               "Canc - Neuroblastoma",
               "Canc - Ovarian",
               "Canc - Pancreas",
               "Canc - Prostate",
               "Canc - Uterine",
               "Canc - Other",
               "Canc - Other (please specify)",
               "Number of Beds"
          from dflisttrim_rbind
          where CompletionStatus="Complete" ')

#output dataframe to a csv file
write.csv(dffinal, file = "~/Desktop/final_output.csv", row.names=FALSE)


